services:
  discord_role_sync:
    image: ghcr.io/antoninhuaut/discordrolesync:master
    container_name: discord_role_sync
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./config.yaml:/app/config.yaml