services:
  discord_role_sync:
    image: ghcr.io/antoninhuaut/discordrolesync:master
    container_name: discord_role_sync
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:8080"
